### ISSUE TITLE
[improvement] make python script output more understandable

### ISSUE THREAD

**Issue by enigma131** [linuxmint/mint20-beta#31]
On terminal output, when you break a command, we have python error instead real reason.

Example, if you abort a install , a end you get a question:
After this operation, 133 MB of additional disk space will be used.
Do you want to continue? [Y/n] n
Abort.

"n" is the normal typing for breaking the install.

If you do "ctrl + c" instread "n" (break command) you have this : 
After this operation, 133 MB of additional disk space will be used.
Do you want to continue? [Y/n] ^CTraceback (most recent call last):
  File "/usr/local/bin/apt", line 165, in <module>
    return_code = subprocess.call(command)
  File "/usr/lib/python3.8/subprocess.py", line 342, in call
    return p.wait(timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1079, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1804, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.8/subprocess.py", line 1762, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt

Is it possible to retrieve the "abort" if we press other keys than "y" or "Y" ?

**Comment by enigma131** [comment]
Fine. Haven't think to post there :)
